Feature/template migration
wif-land/gendocsv3_frontend pull request #71
Opened 2024-09-19 22:26 UTC by SrPabvliss

2024-09-19 23:09 UTC, Leninner commented
> _ No description provided. _

2024-09-19 23:14 UTC, Leninner requested changes
acola viendo los comentarios @SrPabvliss

2024-09-19 23:14 UTC, Leninner commented on src/features/processes/domain/entities/IProcessFilters.ts
> +  field?: string
este cambio no rompe compatibilidad con otros lugares que también usen esta interfaz?

2024-09-19 23:14 UTC, Leninner commented on src/features/templates/data/datasource/TemplatesDatasource.ts
> +    templateIds: number[],
se va a poder migrar solo ciertos templates y no todos los templates pertenecientes a un proceso?

2024-09-19 23:14 UTC, Leninner commented on src/features/templates/data/datasource/TemplatesDatasource.ts
> +    processValue: string | number,
processValue quiere decir que es el código del proceso?

2024-09-19 23:14 UTC, Leninner commented on src/features/templates/presentation/components/ConfirmMigrationDialog.tsx
> +              setSelectedProcess(Number(newValue?.id))
si no existe el ID, y se setea un valor NaN, qué ocurre?

2024-09-19 23:14 UTC, Leninner commented on src/features/templates/presentation/hooks/useMigrateProcess.tsx
> +  const [inputValue, setInputValue] = useState('' as string)
saquemos el as string

2024-09-19 23:14 UTC, Leninner commented on src/features/templates/presentation/hooks/useMigrateProcess.tsx
> +    if (isOpen.value === false) return
if (!isOpen.value) return

2024-09-19 23:51 UTC, SrPabvliss commented on src/features/processes/domain/entities/IProcessFilters.ts
> +  field?: string
no presentó problemas al momento, de hecho ese cambio lo habiamos hecho en otros módulos hace tiempo, al cambio de nombre tengo entendido que se hizo en todos los lugares donde se utilizaba gracias al renombrado en la misma interfaz

2024-09-19 23:54 UTC, SrPabvliss commented on src/features/templates/data/datasource/TemplatesDatasource.ts
> +    templateIds: number[],
todos los que se selecciona dentro de un mismo proceso, si le das al cuadro de selección del header se marcan todas, además las templates nunca las paginamos así que si deberíamos ser capaces de mover todas las templates de un proceso a otro. Psdt: tengo entendido que el mismo hecho de migrar una template es un improbable

2024-09-19 23:55 UTC, SrPabvliss commented on src/features/templates/data/datasource/TemplatesDatasource.ts
> +    processValue: string | number,
La cuestión es que básicamente o bien puede ser el nombre del nuevo proceso o el id de un proceso existente, de ahi el nombre de la variable, en la siguiente parte se utiliza el type of de esta para determinar el nombre que se va a pasar el back que puede ser processId (number) o processName(string)

2024-09-19 23:57 UTC, SrPabvliss commented on src/features/templates/presentation/components/ConfirmMigrationDialog.tsx
> +              setSelectedProcess(Number(newValue?.id))
Excelente pregunta, no lo sé, peor de momento solo se va a mostrar la lista de procesos existentes, por lo tanto no sé qué tan posible sea que sucede. Habría que intentar que suceda para ver.

2024-09-20 00:01 UTC, SrPabvliss commented on src/features/templates/presentation/hooks/useMigrateProcess.tsx
> +    if (isOpen.value === false) return
esta me un poco de coso, a veces suele comprobar existencia en vez de valor y por eso no lo suelo hacer así

2024-09-20 00:07 UTC, Leninner commented on src/features/templates/presentation/hooks/useMigrateProcess.tsx
> +    if (isOpen.value === false) return
Es que aqui hablamos de boolean y si no existe el valor pues seria false

2024-12-09 04:00 UTC, merged